name: Build and Deploy JAR app to Azure Web App - AlphaSolutions-AK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 'java17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

      - name: Set up application properties
        run: |
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_WORKSPACE/application.properties
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_WORKSPACE/application.properties
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_WORKSPACE/application.properties

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_21C41F522E8B4F03A2A5B970B5E6F0DF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_73B348B9F06A4C9FBD8E89AFF779BFA7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E3EC86FBE4F047F298E1C8A4909E4A98 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'AlphaSolutions-AK'
          slot-name: 'Production'
          package: '${{ github.workspace }}/target/*.jar'
